### ISSUE TITLE
Not found Perspective image.

### ISSUE THREAD

**Issue by TuTinh** [minhquan23102000/Vietnamese_IdCard_Image_Extraction#1]
Can you explain it to me?

![image](https://user-images.githubusercontent.com/53398102/154647991-e4619b06-dc86-4eb2-b52f-9d0231c26003.png)

**Comment by minhquan23102000** [comment]
Hi Tu,
Thanks for contacting me!
About your question, you can read two documents bellow:
Homography in computer vision explained - YouTube
<https://www.youtube.com/watch?v=MlaIWymLCD8> (Video)
OpenCV: Basic concepts of the homography explained with code
<https://docs.opencv.org/4.x/d9/dab/tutorial_homography.html> (Paper)

Happy reading!!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by TuTinh** [comment]
Thankyou!
